verify sha1 checksums, and clean stuff up
[finishes #117843235]

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # vim: set ft=sh
 
 set -e
@@ -33,32 +33,40 @@ fi
 
 mkdir -p $destination
 
-download_url="https://bosh.io/d/github.com/${repository}?v=${version}"
-sha1=$(
-  curl \
-    --retry 5 \
-    --fail \
-    --location \
-    "https://bosh.io/api/v1/releases/github.com/${repository}" \
-  | jq \
-    --raw-output \
-    --arg version $version \
-    '.[] | select(.version==$version) | .sha1 // ""'
-  )
+release_data=$(mktemp $TMPDIR/bosh-io-release.XXXXXX)
 
-echo "$download_url" > $destination/url
+curl \
+  --silent \
+  --retry 5 \
+  --fail \
+  --location \
+  "https://bosh.io/api/v1/releases/github.com/${repository}" | \
+  jq 'map(select(.version == $version))[0]' --arg version "$version" > \
+  $release_data
+
+url="$(jq -r .url < $release_data)"
+sha1="$(jq -r .sha1 < $release_data)"
+
+if [ "$url" = "null" ]; then
+  echo "version $version not found; aborting"
+  exit 1
+fi
+
+echo "$url" > $destination/url
 echo "$version" > $destination/version
 echo "$sha1" > $destination/sha1
 
 if [ "$fetch_tarball" = "true" ]; then
-  curl --retry 5 --fail -L "$download_url" -o $destination/release.tgz
+  pushd $destination >/dev/null
+    curl --retry 5 --fail -L "$url" -o release.tgz
+    echo "$sha1  release.tgz" | sha1sum -c -
+  popd >/dev/null
 fi
 
 jq -n '{
-  version: {
-    version: $version
-  },
+  version: { version: $version },
   metadata: [
-    {name: "url", value: $url, sha1: $sha1}
+    { name: "url", value: $url },
+    { name: "sha1", value: $sha1 }
   ]
-}' --arg version "$version" --arg url "$download_url" --arg sha1 "$sha1" >&3
+}' --arg version "$version" --arg url "$url" --arg sha1 "$sha1" >&3
